### ISSUE TITLE
Code samples need to be more detailed

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2-docs#20]
Example: https://developer.blackbaud.com/stache/components/action-buttons

To non-technical users, just giving the properties isn't enough. Ideally, you'd have a code sample with those properties used so they can copy/paste/edit/use.

**Comment by Blackbaud-SteveBrush** [comment]
Moved to Stache2, https://github.com/blackbaud/stache2/issues/201
