### ISSUE TITLE
Add how to use your own custom SCSS (CSS)

### ISSUE THREAD

**Issue by Blackbaud-LindseyRix** [blackbaud/stache2-docs#21]
It's common for people to want to overwirte or add new CSS files. We should extract this from SKYUX stuff and call out how to do it in plain language. 

1. Create this file.
2. Save to this location.
3. Reference it this file.

Maybe explain you can do CSS in SCSS file. Any other tips.

**Comment by Blackbaud-SteveBrush** [comment]
Moved to Stache2, https://github.com/blackbaud/stache2/issues/200
