### ISSUE TITLE
Document Layouts

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud/stache2-docs#8]
{
      name: 'Layout',
      route: '/contribute/components/layout',
      icon: 'map-o',
      summary: 'Component interface between the stache wrapper and layouts.'
    },
    {
      name: 'Layout: Blank',
      route: '/contribute/components/layout-blank',
      icon: 'map-o',
      summary: 'Basic page layouts using Stache and skyux pattern, for quick page layouts.'
    },
    {
      name: 'Layout: Container',
      route: '/contribute/components/layout-container',
      icon: 'map-o',
      summary: 'Basic page layouts using Stache and skyux pattern, for quick page layouts.'
    },
    {
      name: 'Layout: Sidebar',
      route: '/contribute/components/layout-sidebar',
      icon: 'map-o',
      summary: 'Basic page layouts using Stache and skyux pattern, for quick page layouts.'
    },

**Comment by Blackbaud-SteveBrush** [comment]
Moved to Stache2, https://github.com/blackbaud/stache2/issues/203
